# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'BookShop' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'Alamofire', '~> 3.4.1'
pod 'SwiftyJSON', '~> 2.3.2'
pod 'SnapKit', '~> 0.30.0.beta2'
  # Pods for BookShop

end
